library(tidyverse)
library(stringr)
install.packages("htmlwidgets")
library(htmlwidgets)

x <- c("apple", "banana", "pear")
str_view(x, "an")
str_view(x, ".a.")

str_view(stringr::words, "^y", match = TRUE)
str_view(stringr::words, "x$", match = TRUE)
str_view(stringr::words, "^...$", match = TRUE)
str_view(stringr::words, ".......", match = TRUE)
str_subset(stringr::words, "^[aeiou]")
str_subset(stringr::words, "^[^aeiou]+$")
str_subset(stringr::words, "[^e]ed$")
str_subset(c("ed", stringr::words), "(^|[^e])ed$")
str_subset(stringr::words, "i(ng|se)$")
length(str_subset(stringr::words, "(cei|[^c]ie)"))
length(str_subset(stringr::words, "(cie|[^c]ei)"))
str_view(stringr::words, "q[^u]", match = TRUE)
x <- c("123-456-7890", "1235-2351")
str_view(x, "\\d\\d\\d-\\d\\d\\d-\\d\\d\\d\\d")
str_view(x, "[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]")
str_view(x, "\\d{3}-\\d{3}-\\d{4}")
